### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Legion2016** [christian-bendiksen/linux-kernel-16ARHA7-sound-patched#2]
Will this enable speakers but break microphone?  Also do I install one asset at a time not including the patch ?

**Comment by christian-bendiksen** [comment]
No this will not break the microphone.

**Comment by christian-bendiksen** [comment]
> Will this enable speakers but break microphone? Also do I install one asset at a time not including the patch ?

No this will not break the microphone. Are you using Fedora?
If you are using Fedora, you can use my [COPR](https://copr.fedorainfracloud.org/coprs/dennemann/legion-16ARHA7-sound-patch/) instead. Add it to your repos and do a `sudo dnf update`.

If you want to use the RPM's, you can install them all with `sudo dnf install ./kernel*`

**Comment by Legion2016** [comment]
I'm currently using nobara. I'm thinking of going with straight fedora so I can use this

**Comment by christian-bendiksen** [comment]
> I'm currently using nobara. I'm thinking of going with straight fedora so I can use this

I think it should work on Nobora. Have you tried enabling the [COPR](https://copr.fedorainfracloud.org/coprs/dennemann/legion-16ARHA7-sound-patch/)?

`sudo dnf copr enable dennemann/legion-16ARHA7-sound-patch`

then doing a update.

`sudo dnf update`

**Comment by Legion2016** [comment]
I followed what you said.  It seemed to install and update. Still no sound.  Is there something else I need to do ?

**Comment by christian-bendiksen** [comment]
> I followed what you said. It seemed to install and update. Still no sound. Is there something else I need to do ?

What kernel are you using now when you type `uname -a` ?

**Comment by Legion2016** [comment]
6.7.6-201.fsync

**Comment by christian-bendiksen** [comment]
> 6.7.6-201.fsync

Did you do a reboot? You need to boot into the new kernel.

**Comment by Legion2016** [comment]
The new kernel is not listed in grub

**Comment by Legion2016** [comment]
It added repo quick,  dnf update was real quick to.  I'm not sure it downloaded a new kernel

**Comment by Legion2016** [comment]
Might be a nobara issue ?

**Comment by christian-bendiksen** [comment]
> Might be a nobara issue ?

What happens if you do `sudo dnf install kernel-6.7.11-200.16ARHA7.fc39` ?

**Comment by Legion2016** [comment]
That works. Thankyou. Now to see what that did to game performance. Nobara uses its own custom kernel with lots of patches for performance.  Still very nice to here them speakers Thankyou so much

**Comment by christian-bendiksen** [comment]
> That works. Thankyou. Now to see what that did to game performance. Nobara uses its own custom kernel with lots of patches for performance. Still very nice to here them speakers Thankyou so much

Great! This is just a standard fedora kernel with the sound fix added. I have sent the patch upstream so hopefully it get merged. Then it should be available on nobara in the future as well.

**Comment by Legion2016** [comment]
I appreciate what you did.  You made my day

**Comment by Legion2016** [comment]
Is there a way to upgrade to new kernel 6.9 now in fedora 40

**Comment by christian-bendiksen** [comment]
> Is there a way to upgrade to new kernel 6.9 now in fedora 40

yes, https://fedoraproject.org/wiki/Kernel_Vanilla_Repositories

This fix will be backported to stable kernels as well, got the email about it yesterday. So should be available soon!

**Comment by Legion2016** [comment]
All I need now is the fingerprint reader and this laptop will be perfect lol
