### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Legion2016** [christian-bendiksen/linux-kernel-16ARHA7-sound-patched#4]
Hope im not overstepping, you came to mind.  This is a long shot.   Maybe you use this laptop. In question.   There is an issue with gpu wattage.   It's maxed at 65 watts.  I found that mine,  the amdgpu driver does not read the acpi,  it reports with dmesg
amdgpu 0000:03:00.0: amdgpu: ACPI VFCT table present but broken (too short #2),skipping.  I thought maybe this the cause of the low wattage cap.    Way over my head.   Was wondering if you had any input, or what steps and where could get attention for such thing.

**Comment by Legion2016** [comment]
I figured it out.  I was using Legion linux tools.  Put it wasn't actually changing profile just had to do it manually. I'm now 90 watts

**Comment by christian-bendiksen** [comment]
I'm currently using the HP spectre. So not using the laptop for a good while now. Also testing out the new Windows 11 24H2 atm. (don't shoot me).

Glad you figured it out!
